### ISSUE TITLE
bug: can't send stdin into terminal that create by command

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/on#9]
It's related to the fix of #4, but anyway #4 is more serious than this one, so won't revert the fix but based on it.

**Comment by dannypsnl** [comment]
Basically, I can handle #4 and #9, but can't deal with both of them at the same time.

**Comment by codenio** [comment]
@dannypsnl please make it more descriptive.

**Comment by dannypsnl** [comment]
Where the problem is, originally I using `go io.Copy(tty, os.Stdin)` to allow a pseudo terminal getting standard input, but that brings a problem:
Because `io.Copy` do not know `tty` be closed, until it `Read` from standard input and try to `Write` bytes into `tty`, the result is it would eat one char at next round.

Now the problem is I try to use `signal.Notify(c)` to get standard input, but just at first char I typed in, the channel closed, so that has no signal can be sent into the opened `tty` caused it just hangs.

@aananthraj Sorry about the misunderstood description, I'm didn't get the point when I open the issue a beginning actually XD.

**Comment by codenio** [comment]
I am trying to understand the problem, meanwhile can you provide some examples (screen shots or terminal outputs).

Steps to replicate the above error/problem would be helpful. 

BTW is this know error ?
```
$ ./on docker
on(docker)> 
# ctrl + c 
on()> 
# enter
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
main.(*History).executor(0xc00007e6c0, 0x524e00, 0x0)
	/home/aananth/go/src/github.com/dannypsnl/on/main.go:70 +0x552
main.(*History).executor-fm(0x524e00, 0x0)
	/home/aananth/go/src/github.com/dannypsnl/on/main.go:26 +0x3e
github.com/c-bata/go-prompt.(*Prompt).Run(0xc0000cc000)
	/home/aananth/go/src/github.com/c-bata/go-prompt/prompt.go:73 +0x764
main.main()
	/home/aananth/go/src/github.com/dannypsnl/on/main.go:34 +0x3fa

```

**Comment by dannypsnl** [comment]
```
$ on kubectl
on(kubectl)>
# ctrl + c
on()>
on()>
on()>
on()>
```

Which version did you use? I guess that' fixed.

**Comment by dannypsnl** [comment]
This bug is found by this use case, I want to enter a pod, but as you can see after I do that, I can't do anything with it.
```
on kubectl
on(kubectl)> get po
NAME                             READY   STATUS    RESTARTS   AGE
alpine-deploy-5694b87b56-kvks5   1/1     Running   0          29h
alpine-deploy-5694b87b56-qbwjv   1/1     Running   0          29h
on(kubectl)> exec -ti alpine-deploy-5694b87b56-kvks5 bash
bash-4.4#
```

**Comment by codenio** [comment]
@dannypsnl tried my level best, but unable to fix the issue. will try to explore and let you know my findings.
Thanks for the prompt response.

**Comment by dannypsnl** [comment]
Idea: call `file.Stat()` to check no error(use Closed file should get the error)
